# Change baseurl before deploy
baseURL = "https://shidanz.github.io/"
locale  = "en-us"
title   = "Joxlyn's Blog"
theme   = "hugo-theme-stack"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[pagination]
    pagerSize = 5
